### ISSUE TITLE
Board meeting dates always misaligned by a week between different pages/resources

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-board#1]
This was a wiki problem, now it's a www2 problem:

1. Visit https://owasp.org/www-board/
2. Note it says 2020-01-28
3. Click the "January 2020 Videoconference" link
4. Note it doesn't display the date at all, but the "Convert" link points to the 21st.

![board_scheduling_wtf](https://user-images.githubusercontent.com/7570458/72804970-c8477380-3c1f-11ea-8f5a-97ec771b044a.gif)

**Comment by mikemccamon** [comment]
This was fixed a while ago. Thanks for finding this and sorry I didn't close it out.
