### ISSUE TITLE
Approximate calendar dates for the General Election Timeline

### ISSUE THREAD

**Issue by cqueern** [OWASP/www-board#28]
Hi Team,

The [list of steps in the General Election Timeline](https://github.com/OWASP/www-board/blob/master/elections/index.md#general-election-timeline) is great! 

Would it be possible to add approximate calendar dates for the steps shown?

**Comment by avidouglen** [comment]
That's a general template timeline, you can find the specific dates here: https://owasp.org/www-board/elections/2022_elections

**Comment by cqueern** [comment]
Thank you @avidouglen! I think I see an error on [that page](https://owasp.org/www-board/elections/2022_elections):

> 08-01-2023 - Any Director-elect who still has not obtained paid membership after the grace period, has not qualified to be a Director. The next most voted candidate will take their place

I think that's supposed to be:

> **01-08**-2023 - Any Director-elect who still has not obtained paid membership after the grace period, has not qualified to be a Director. The next most voted candidate will take their place

**Comment by avidouglen** [comment]
@cqueern you're only saying that because you're American ;-) 
Yes it should be January 8th, but I think a lot of those dates are ambiguous globally - I think that this should be added to policy: https://xkcd.com/1179/
:-)

**Comment by cqueern** [comment]
Fair point :) and agreed it would be good to standardize globally. 

Seemed like all the other dates listed [on the page](https://owasp.org/www-board/elections/2022_elections) are in MM-DD-YYYY format so it might make sense to have the final one conform as well.
