### ISSUE TITLE
Jan 2020 Minutes/Votes?

### ISSUE THREAD

**Issue by kingthorin** [OWASP/www-board#4]
Neither the voting tab nor historic tab seem to have details from January's meeting, and we're 5 days from February's meeting.
https://owasp.org/www-board/#div-voting
https://owasp.org/www-board/#div-historical

**Comment by mikemccamon** [comment]
https://owasp.org/www-board/minutes/202001

We didn't add a tab for minutes but they will always show up in ../minutes when they are ready for Board approval. We were going to make this automatically show up on the Board page - maybe we should after all.
